In Python we have lists that serve the purpose of arrays, but they are slow to process.

#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

### create array

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#two dimension array 

In [7]:
#1
two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [12]:
#2
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)

[[1 2 3 4]]


In [ ]:
#ndim 
#dimentions

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
print(b)

[1 2 3 4 5]


In [10]:
print(np.zeros((2, 3)))           # 2x3 array with all elements 0
print (np.ones((1,2))  )           # 1x2 array with all elements 1
print(np.full((2,2),7)  )         # 2x2 array with all elements 7
print(np.eye(2)  )                # 2x2 identity matrix

print(np.arange(10) )             # Evenly spaced values in an interval
print(np.linspace(0,9,10) )       # same as above, see exercise

c = np.ones((3,3))
d = np.ones((3, 2), bool)  # 3x2 boolean array

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
c 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#1Try out np.arange(10) and np.linspace(0,9,10), what is the difference? Can you adjust one to do the same as the other?

In [33]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
np.linspace(start =0, stop = 10, num =9)


array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#Datatypes Create a 3x2 array of random float numbers (check numpy.random.random()) between 0 and 1. Now change the arrays datatype to int (array.astype). How does the array look like?

In [55]:
from numpy import random


In [ ]:
#float array
random.rand
#integer array
random.int

In [59]:
x=random.rand(3,2)
print(x)

[[0.3373698  0.37245249]
 [0.03659053 0.58533559]
 [0.33123887 0.85326747]]


In [60]:
#change it to int
a=x.astype('int')
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
#Reshape Create a 3x2 array of random integer numbers between 0 and 10. Reshape the array in any way possible. What is not possible?

In [64]:
npint=random.randint(10,size=(3,2))
print(npint)

[[9 7]
 [2 2]
 [8 2]]


In [66]:
b = np.random.randint(0,10,(3,2))
print(b)

[[8 9]
 [4 5]
 [6 4]]


In [67]:
b.reshape((6,1))

array([[8],
       [9],
       [4],
       [5],
       [6],
       [4]])

In [ ]:
#Array maths


In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = a + b
print(c) 



[[ 6  8]
 [10 12]]


In [78]:
d = np.multiply(a,b)
print (d)

[[ 5 12]
 [21 32]]


In [79]:
e = np.dot(a,b)
print (e)

[[19 22]
 [43 50]]


In [ ]:
impertant

In [ ]:
#Matrix multiplication np.multiply does elementwise multiplication on two arrays, while np.dot enables matrix multiplication.

In [ ]:
#Array maths


a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = a + b
print(c) 



d = np.multiply(a,b)
print (d)

e = np.dot(a,b)
print (e)

impertant

#Matrix multiplication np.multiply does elementwise multiplication on two arrays, while np.dot enables matrix multiplication.

In [ ]:
# type of numby

In [25]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [27]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [7]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#astype

In [8]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# type of numby

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

#astype

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

### indexing

In [2]:
#accessing elments

In [3]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 0, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
8


In [18]:
#Indexing and Slicing
a = np.arange(16).reshape(4, 4) 
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
print(a[1:3,1:3]    )                   # middle 2x2 array


[[ 5  6]
 [ 9 10]]


In [16]:
a = np.arange(16).reshape(4, 4) 
print(a)# 4x4 matrix from 0 to 15
print(a[0]  )                           # first row
print(a[:,0]   )                        # first column
print(a[1:3,1:3]    )                   # middle 2x2 array

a[(0, 1), (1, 1)]  

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 0  4  8 12]
[[ 5  6]
 [ 9 10]]


array([1, 5])

In [17]:
print(a[1:3,1:3]    )                   # middle 2x2 array


[[ 5  6]
 [ 9 10]]


In [ ]:
a = np.eye(4)
b = a[:,0]
b[0] = 5

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [21]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [24]:
#From both elements, return index 2:


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


### slicing

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
#Slicing 2-D Arrays


In [24]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

### copy

In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### view

In [31]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
#Check if Array Owns it's Data


In [33]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Shape 

In [36]:
arr=np.array([[1,2,2],[3,4,5]])

In [38]:
print(arr.shape)

(2, 3)


In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 2, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Flattening the arrays


In [45]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Iterating Arrays


In [47]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [50]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [ ]:
#nditer

In [51]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [ ]:
#ndenumerate

In [52]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### random number

In [57]:
x = random.rand()

print(x)

0.5136124122145942


In [55]:
x = random.randint(100)

print(x)

35


In [56]:
x=random.randint(100, size=(5))

print(x)

[34 75 69 82 26]


In [58]:
x = random.randint(100, size=(3, 5))

print(x)

[[90 48  2 85 75]
 [38 77 74 84 32]
 [66 37 32 70  6]]


In [59]:
x = random.rand(5)

print(x)

[0.5191846  0.25650988 0.94513619 0.77319808 0.92419517]


In [ ]:
x = numpy.random.uniform(0.0, 5.0, 250)

plt.hist(x, 5)
plt.show()

## from numpy to pandas

In [49]:
dd=np.array(["ss","pp"])

In [56]:
#dd[1]
print(dd)

['ss' 'pp']


In [53]:
ss=pd.Series(["ss","pp"])

In [57]:
ss[1]
print(ss)

0    ss
1    pp
dtype: object


In [60]:
pan=pd.DataFrame(dd)

In [61]:
type(pan)

pandas.core.frame.DataFrame

In [57]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr)

newarr = np.array_split(arr, 3)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#NumPy Searching Arrays


In [58]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
#Which means that the value 4 is present at index 3, 5, and 6.



There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.



In [68]:
#Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [59]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [66]:
x = np.array([1, 2, 3])
id(x)                        # get the memory-ID of x
#np.add(x, x, x)              # Third argument is output array
np.add(x, x, x)
print(x)
id(x)                        # get the memory-ID of x
                             # - notice  it is the same

[ 4  8 12]


2391065845552

In [51]:
x = np.array([1, 2, 3])
id(x)

2391007581648

In [52]:
np.add(x, x, x)              # Third argument is output array


array([2, 4, 6])

In [ ]:
#NumPy ufuncs


ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [60]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [61]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [62]:
def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [63]:
myadd

<ufunc 'myadd (vectorized)'>

In [64]:
print(type(np.add))

<class 'numpy.ufunc'>


Simple Arithmetic


In [ ]:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

#newarr = np.subtract(arr1, arr2)
newarr = np.add(arr1, arr2)
newarr = np.multiply(arr1, arr2)
newarr = np.divide(arr1, arr2)
newarr = np.mod(arr1, arr2)
newarr = np.remainder(arr1, arr2)
newarr = np.divmod(arr1, arr2)
newarr = np.absolute(arr)

print(newarr)

Rounding Decimals


In [ ]:
arr = np.trunc([-3.1666, 3.6667])
arr = np.fix([-3.1666, 3.6667])
arr = np.floor([-3.1666, 3.6667])

print(arr)

## NumPy Joining Array


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

#arr = np.stack((arr1, arr2), axis=1)
#arr = np.hstack((arr1, arr2))
#arr = np.Vstack((arr1, arr2))
arr = np.dstack((arr1, arr2))

print(arr)

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [1]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball

np_baseball=np.array(baseball)
# Print out type of np_baseball
print(np_baseball)


[180 215 210 210 188 176 209 200]


In [ ]:
### Subsetting NumPy Arrays
